// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqOSZpGphYMrNCXCtg-UweC29YdSpyYQk',
    appId: '1:160852200811:web:4f33f27c412394e320d02e',
    messagingSenderId: '160852200811',
    projectId: 'heritageimm-ad896',
    authDomain: 'heritageimm-ad896.firebaseapp.com',
    storageBucket: 'heritageimm-ad896.appspot.com',
    measurementId: 'G-D2LJ1DC3MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFYJsFvoq3Dysz2h-b9F6SPgOA4AUzeQU',
    appId: '1:160852200811:android:9ef8a92d987c763d20d02e',
    messagingSenderId: '160852200811',
    projectId: 'heritageimm-ad896',
    storageBucket: 'heritageimm-ad896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ky9YLat1f-H8Td8A80LJMH1nXvaBSQ0',
    appId: '1:160852200811:ios:04d2847a3f8543c520d02e',
    messagingSenderId: '160852200811',
    projectId: 'heritageimm-ad896',
    storageBucket: 'heritageimm-ad896.appspot.com',
    iosClientId: '160852200811-2ciamqtbdk1lmmt8ikcqsjtav3taqhlp.apps.googleusercontent.com',
    iosBundleId: 'com.chetan.heritage',
  );
}
