abstract class Strings {
  String get cantBeEmpty ;
  String get appName ;
  String get tooShort ;
  String get notValidEmail ;
  String get enterEmail ;
  String get email ;
  String get submit ;
  String get login ;
  String get welcome ;
  String get invalidPin ;
  String get firstName ;
  String get lastName ;
  String get phonenumber ;
  String get dateOfBirth ;
  String get DDMMYYYY ;
  String get pincode ;
  String get save ;
  String get hintphoneNumber ;
  String get phoneNumberPrefix ;
  String get enterValidPhoneNumber ;
  String get birthDateisEmpty ;
  String get monthIsinvalid ;
  String get dayIsinvalid ;
  String get yearIsinvalid ;
  String get forgotPassword ;
  String get enterEmailToFetchTheDetail ;
  String get enterPassword ;
  String get enterNewPassword ;
  String get setPassword ;
  String get enterConfirmPassword;
  String get passwordNotMatch;
  String get minimum8Charcter;
  String get pleaseEnterValidPincode;
  String get pleaseEnterAllDetail;
  String get newUser;
  String get newUserAdded;
  String get registerSuccessfully;
  String get loginSuccessfully;
  String get profileUpdated;
  String get verificationEmailSent;
  String get resetPasswordEmail;
}