abstract class Strings {
  String get cantBeEmpty ;
  String get appName ;
  String get tooShort ;
  String get notValidEmail ;
  String get enterEmail ;
  String get email ;
  String get submit ;
  String get login ;
  String get welcome ;
  String get invalidPin ;
  String get firstName ;
  String get name ;
  String get lastName ;
  String get phonenumber ;
  String get dateOfBirth ;
  String get DDMMYYYY ;
  String get pincode ;
  String get save ;
  String get hintphoneNumber ;
  String get phoneNumberPrefix ;
  String get enterValidPhoneNumber ;
  String get birthDateisEmpty ;
  String get monthIsinvalid ;
  String get dayIsinvalid ;
  String get yearIsinvalid ;
  String get forgotPassword ;
  String get enterEmailToFetchTheDetail ;
  String get enterPassword ;
  String get enterNewPassword ;
  String get setPassword ;
  String get enterConfirmPassword;
  String get passwordNotMatch;
  String get minimum8Charcter;
  String get pleaseEnterValidPincode;
  String get pleaseEnterAllDetail;
  String get newUser;
  String get newUserAdded;
  String get registerSuccessfully;
  String get loginSuccessfully;
  String get profileUpdated;
  String get verificationEmailSent;
  String get resetPasswordEmail;


  //student form string


  String get studentForm ;
  String get selectDate ;
  String get date;
  String get passportExpiryDate;
  String get enterName;
  String get refferedby;
  String get DOB;
  String get hintName;
  String get hintCityName;
  String get cityVillage;
  String get enterStudentContactNo;
  String get enterParentContactNo;
  String get enterStudentemail;
  String get enterParentemail;
  String get numberOfChildren;
  String get married;
  String get paymentReceived;
  String get emailHint ;
  String get zero ;
  String get manager  ;
  String get spousesName ;
  String get spousesOccupation  ;
  String get fathersOccupation  ;
  String get mothersOccupation  ;
  String get fathersName ;
  String get mothersName  ;
  String get netFamilyIncomeAnnually ;
  String get educationalInformation;
  String get tenth;
  String get twelveth;
  String get monthyearDateFormat;
  String get fromMMYYYY;
  String get toMMYYYY  ;
  String get stream ;
  String get scienceHistory ;
  String get boardUniversityCollege  ;
  String get CBSE ;
  String get percentage ;
  String get percentageHint ;
  String get noofBacklogsifany ;
  String get assessmentInformation ;
  String get criminalHistory ;
  String get dubai ;
  String get CountryIfapplicable ;
  String get travelHistory ;
  String get anyRefusals ;
  String get IELTSGenAca ;
  String get yearFormat ;
  String get year ;
  String get L ;
  String get R ;
  String get W ;
  String get S ;
  String get OA ;
  String get eight ;
  String get IDPBC ;
  String get next ;
  String get add ;
  String get anyProvincePreferenceInCanadaIfNoThenMentionNONE ;
  String get canadianUniversity ;
  String get anyCollegeProgramPreferenceIFNoThenMentionNONE ;
  String get userDetail ;
  String get remark ;
  String get nameOfAdvisor ;
  String get comment ;
  String get createdAt ;
  String get updatedAt ;
  String get customerComment ;
  String get employeeComment ;
  String get addUser ;
  String get notificatons ;
  String get setting ;
  String get chatDeleteTime ;
  String get passportNotiFicationTime ;
  String get admins ;
  String get update ;
  String get addAdmins ;
}